[build-system]
requires = ["setuptools"] 
build-backend = "setuptools.build_meta"

[project]
name = "bondbert"
version = "2025.0.0"
description = "An ensemble framework for materials science NLP"
readme = "README.md"
authors = [{name = "Isabella Crouch"}]